unique_ids:
  forms:
    Form1: 63XCHUZQD7MYY3KOVIE5Y7MVIDJZ6H5Q
  modules: {}
  server_modules: {}
  assets:
    6499468f33db295c5a1219ec_Ultralytics_mark_blue.svg: '1721087926938597458541845.2529'
    standard-page.html: IQKCWE4KEB2SVXJXG7XYIVA63Y5RKYCR
    theme.css: 72BI7PHTEAMZFR4PEGFNGSV5SKMYGZQ7
  scripts: {}
